### ISSUE TITLE
PowerShell resources erroring out

### ISSUE THREAD

**Issue by AmarettoSlim** [puppetlabs/ruby-pwsh#196]
Hi puppetlabs,

I'm hoping someone could help me out here, I have a system that is exhibiting the same behavior (powershell resources erroring out) and message reported in issue #188, but we're already running the latest version of ruby-pwsh. I confirmed the code that prevents SystemRoot from being cleaned up is present on the box. We have "PowerShell Script Block Logging" enabled but do not use ""Protected Event Logging".

I recognize that because I don't know what setting(s) are causing this, reproducing is difficult / impossible but if someone could share how I can troubleshoot this on the machine, that would be appreciated.

Thanks!

**Error Sample**
`PS C:\Users> puppet agent -t -v
Info: Using environment 'ex_production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for server100.sub.domain.com
Info: Applying configuration version '1664544632'
#<Thread:0x000000000a41ae10 C:/ProgramData/PuppetLabs/puppet/cache/lib/pwsh.rb:561 run> terminated with exception (repor
t_on_exception is true):
Traceback (most recent call last):
        1: from C:/ProgramData/PuppetLabs/puppet/cache/lib/pwsh.rb:563:in `block in read_streams'
C:/ProgramData/PuppetLabs/puppet/cache/lib/pwsh.rb:563:in `sysread': end of file reached (EOFError)
#<Thread:0x0000000009dd7ee0 C:/ProgramData/PuppetLabs/puppet/cache/lib/pwsh.rb:561 run> terminated with exception (repor
t_on_exception is true):`

**Comment by AmarettoSlim** [comment]
Hi @chelnak  - thanks for the reply, here is the information you're looking for:

ruby-pwsh version - 0.10.2
Operating System - Windows Server 2016 Datacenter (10.0.14393 Build 14393)
Puppet Version - 7.4.2
Puppet Agent Version - 7.13.1

**Comment by kenyon** [comment]
@AmarettoSlim did you figure this out? I started getting this on some newly-provisioned Windows 10 21H2 machines. Nothing in my Puppet environment related to PowerShell has changed AFAIK, and my Windows team hasn't reported any GPO changes.

**Comment by kenyon** [comment]
Turns out this was caused by our allowlisting security software Airlock Digital 😢. It was preventing access to RubyPwsh.cs, which I determined by running init.ps1 manually and seeing the powershell "access to the path is denied" error/exception.
